### ISSUE TITLE
Notification history

### ISSUE THREAD

**Issue by cro** [waffleio/waffle.io#1199]
We need a notification history pane that shows the most recent notifications and allows a user to click through to the notification source.

It's quite frustrating to see the popup but not be able to do anything with it, and also have it disappear before your brain can fully process it.

**Comment by patrickpenn** [comment]
+1
We use waffle for a simple but effective agile project management. Because we're using small tasks and retrieve new customer request with high priority, we should be able to see the last changes on the board. Highlighting the issue on the board while hovering over the notification history would be great. Hope to see this feature soon.

**Comment by meatballs** [comment]
+1 from me

**Comment by meatballs** [comment]
+1

**Comment by armilam** [comment]
:+1:

**Comment by daniellawman** [comment]
+1

**Comment by mrucevic** [comment]
+1

**Comment by Tomivav** [comment]
+1

**Comment by Tomivav** [comment]
+1

**Comment by scottdelly** [comment]
+1

**Comment by maxcan** [comment]
+1.  Its a shame that this has been open for 2 years.  It seems rather simple to implement.  At least from a "labs" point of view where a prototype with a very simple interface is offered.

**Comment by 5app-James** [comment]
+1

**Comment by 5app-James** [comment]
The notification pop-up only lasts a second and I often fail to click on it in time. The only way to know what happened is to check my GitHub emails.

**Comment by mkeppel** [comment]
+1  Just saw a notification pop up while working on a different issue tried to find a way to see what it was and that was a dead end no way to get back to it or see what it was.

**Comment by Slind14** [comment]
+1

**Comment by stephanielanning** [comment]
+1

**Comment by homeyer** [comment]
Closing this, as it's solved by our slack integration. Cheers!

**Comment by pmz** [comment]
What? No that's not solved. Having to use Slack isn't a solution.
Please reconsider implementing a notification pane.

**Comment by ndkv** [comment]
The Slack integration is unfortunate as we do not use Slack. Also, having the notifs in the browser would allow for highlighting of cards that have e.g. new comments. Having the notifs outside of Waffle results in a constant switching between my email client, Waffle and GitHub as the notif emails only contain links to GitHub (since they generate them) and not to Waffle. 

Can you indicate what the implications would be for Waffle to implement this feature? For example, I've the feeling that you do not store the notifications but "simply" send them to the browser and Slack, correct?
