### ISSUE TITLE
[Support] Waffle silently fails to move issues

### ISSUE THREAD

**Issue by yaronyg** [waffleio/waffle.io#2185]
I moved an issue from one column to another. The UX showed the card in the new column and I didn't get an error message. Then I changed the filter and suddenly the issue was back in the column I had dragged it from. This is absolutely death for us! We can't use an issue system that silently undoes what we do without any kind of error.

**Comment by ashumz** [comment]
Hi @yaronyg, 

Apologies for a delay in response. Are you still seeing this? We believe it was unintended behavior from ranking issues that we fixed this past Friday (#2126). If you continue to see cards not get the proper column placement/labels, please let us know right away. 

Ashley

**Comment by yaronyg** [comment]
What we are now seeing is something slightly different and I'm not sure if it's the same issue or not. What we see now is that an issue gets moved and the label is right but it's still shown in the wrong column. If you do a refresh or change the filter then sometimes it will show the issue in the right column but not always. But we can see that the tag is right. This is mostly happening with closed issues (e.g. they are still in progress instead of in closed even though they are closed in Github) but we have also seen it with other tags.

**Comment by kellihsf** [comment]
Hey there,

We have fixed these issues, sorry about the trouble!

**Comment by Ankita00** [comment]
This problem still appears in one of the public repo. Has the issue not been resolved yet? Please respond.

**Comment by kellihsf** [comment]
hi @Ankita00,

We have responded to your email about this through our in-app messaging system. We'll continue to correspond with you through there. :)
